# Generated by Django 4.1.5 on 2023-01-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageEditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='about_property',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='option',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='price',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
